/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  mainnetsSidebars: [
    {
      type: "autogenerated",
      dirName: ".", // This must remain `.` if your new docs instance is in the base directory
    },
    // {
    //   type: "category",
    //   label: "Atomone",
    //   link: {
    //     type: "doc",
    //     id: "mainnets/atomone",
    //   },
    //   collapsible: true,
    //   items: [{ type: "autogenerated", dirName: "mainnets/atomone" }],
    //   // className: "sidebar-section-with-icon icon-atomone",
    // },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
